# Generated by Django 5.1.7 on 2025-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fitness_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight-loss", "Weight Loss"),
                    ("muscle-gain", "Muscle Gain"),
                    ("endurance", "Endurance"),
                    ("flexibility", "Flexibility"),
                    ("general", "General Fitness"),
                ],
                max_length=20,
                null="General Fitness",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free Trial"),
                    ("basic", "Basic Plan"),
                    ("premium", "Premium Plan"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
