# Generated by Django 5.1.7 on 2025-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_fitness_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
    ]
