# Generated by Django 5.1.7 on 2025-03-20 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciselog",
            name="workout_log",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="workout",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="muscle_group",
        ),
        migrations.RemoveField(
            model_name="exerciselog",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="rest_time",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="title",
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="reps_completed",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="rest_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="name",
            field=models.CharField(default="Default Workout Plan", max_length=100),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_images"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exerciselog",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="reps",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="sets",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="duration_weeks",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name="UserWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("calories_burned", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="user_workout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_logs",
                to="fitness.userworkout",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_days",
                        to="fitness.workoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.AddField(
            model_name="userworkout",
            name="workout_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fitness.workoutday"
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="workout_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="fitness.workoutday",
            ),
        ),
        migrations.DeleteModel(
            name="UserWorkoutLog",
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
    ]
